baseURL = "/"
title = "TOPS GUIDE"
theme = "saasify"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true

[languages.ru]
  languageCode = "ru-RU"
  languageName = "Русский"
  weight = 1

    [[languages.ru.menus.main]]
      identifier = "first_step"
      name = "Первые шаги"
      pageRef = "/first_step"
      weight = 1
    [[languages.ru.menus.main]]
      identifier = "mods"
      name = "Моды"
      pageRef = "/mods"
      weight = 2
    [[languages.ru.menus.main]]
      identifier = "guide"
      name = "Гайды"
      pageRef = "/guide"
      weight = 3
    [[languages.ru.menus.main]]
      identifier = "map"
      name = "Карта"
      pageRef = "/map"
      weight = 4
    [[languages.ru.menus.main]]
      identifier = "tourism"
      name = "Города и туризм"
      pageRef = "/tourism"
      weight = 5
[[languages.ru.menus.main]]
      parent = "tourism"        # ссылаемся на identifier родителя
      name = "Города"
      pageRef = "/tourism/towns"
      weight = 51
[[languages.ru.menus.main]]
  identifier = "telegram"
  name = "РУ ТГ"
  url = "https://t.me/mylesvintagestory"
  weight = 99

  # RU: тексты/ссылки CTA
  [languages.ru.params.header.buttons.signIn]
    text = "Все для чизла"
    url  = "https://chisel-beta.vercel.app/"
  [languages.ru.params.header.buttons.getStarted]
    text = "Связаться со мной"
    url  = "/call_me"

[languages.en]
  languageCode = "en-US"
  languageName = "English"
  weight = 2
  
    [[languages.en.menus.main]]
      identifier = "first_step"
      name = "First steps"
      pageRef = "/first_step"
      weight = 1
    [[languages.en.menus.main]]
      identifier = "mods"
      name = "Mods"
      pageRef = "/mods"
      weight = 2
    [[languages.en.menus.main]]
      identifier = "guide"
      name = "Guide"
      pageRef = "/guide"
      weight = 3
    [[languages.en.menus.main]]
      identifier = "map"
      name = "Map"
      pageRef = "/map"
      weight = 4
    [[languages.en.menus.main]]
      identifier = "tourism"
      name = "Towns and tourism"
      pageRef = "/tourism"
      weight = 5
[[languages.en.menus.main]]
      parent = "tourism"        # ссылаемся на identifier родителя
      name = "Towns"
      pageRef = "/tourism/towns"
      weight = 51

  # EN: тексты/ссылки CTA
  [languages.en.params.header.buttons.signIn]
    text = "All for chiseling"
    url  = "https://chisel-beta.vercel.app/"
  [languages.en.params.header.buttons.getStarted]
    text = "Contact me"
    url  = "/call_me"

[params.header]
  background = "bg-white/80 backdrop-blur-sm"
  border = "border-b border-gray-100"
  [params.header.logo]
    src = "/images/logo.png"
  [params.header.menu]
    spacing = "space-x-8"
  [params.header.buttons]
    [params.header.buttons.signIn]
      text = "Sign in"
      url = "/signin"
      class = "inline-flex items-center justify-center px-5 py-2.5 rounded-xl font-semibold border border-slate-200 hover:border-blue-600 hover:text-blue-600 transition"
      mobileClass = "block text-center px-5 py-2.5 rounded-xl font-semibold border border-slate-200 hover:border-blue-600 hover:text-blue-600 transition"
    [params.header.buttons.getStarted]
      text = "Get Started"
      url = "/get-started"
      class = "inline-flex items-center justify-center px-5 py-2.5 rounded-xl font-semibold bg-blue-600 text-white hover:bg-blue-700 transition"
      mobileClass = "block text-center px-5 py-2.5 rounded-xl font-semibold bg-blue-600 text-white hover:bg-blue-700 transition"

# Соц-сети для иконок в подвале
  [params.social]
    github   = "https://github.com/Metalismaticus"
    discord  = "https://discord.com/users/698122435266084975"

  # Настройки подвала
  [params.footer]
    brand_name = ""
    brand_logo = ""        # можно опустить, если хватает title
    credit_text = "Designed by Metalismatic"
    credit_url  = "https://t.me/yourprofile"

    # Заголовки колонок (проще так, без i18n)
# Меню трёх колонок подвала
[menu]
  # Колонка 1
  [[menu.footer_column_1]]
    name = "GitHub"
    url  = "https://github.com/Metalismaticus"
    weight = 1
  [[menu.footer_column_1]]
    name = "Map"
    url  = "/map"
    weight = 2
  [[menu.footer_column_1]]
    name = "Docs"
    url  = "/docs"
    weight = 3

  # Колонка 2
  [[menu.footer_column_2]]
    name = "Telegram"
    url  = "https://t.me/yourchannel"
    weight = 1
  [[menu.footer_column_2]]
    name = "Discord"
    url  = "https://discord.gg/yourinvite"
    weight = 2
  [[menu.footer_column_2]]
    name = "About"
    url  = "/company"
    weight = 3

  # Колонка 3
  [[menu.footer_column_3]]
    name = "License"
    url  = "/license"
    weight = 1
  [[menu.footer_column_3]]
    name = "Privacy Policy"
    url  = "/privacy"
    weight = 2

[params.header.menu.dropdown]
  width = "w-72"
  container_padding = "py-3"
  background = "bg-white/5 backdrop-blur-md"
  border = "ring-1 ring-white/10"
  shadow = "shadow-xl"
  radius = "rounded-xl"
  text_color = "text-white/90"
  hover_background = "hover:bg-white/10"
